project_id = "wugzcmqtlctrccixqpvf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
port = 54327
site_url = "https://kunda-pathways.vercel.app"
additional_redirect_urls = ["https://kunda-pathways.vercel.app/admin/reset-password", "https://kunda-pathways.vercel.app/reset-password", "http://127.0.0.1:3000", "https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54328
inspector_port = 8083

[functions.aria-chat]
verify_jwt = false

[functions.send-reply-email]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false