import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";

interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  translations: Translations;
}

const translations = {
  EN: {
    welcome: "Welcome",
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    resources: "Resources",
    blog: "Blog",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    sitemap: "Sitemap",
    studyInKorea: "Study in Korea",
    fbConsulting: "F&B Consulting",
    universityAdmissions: "University Admissions",
    marketAnalysis: "Market Analysis",
    backToHome: "Back to Home",
    resourcesBlog: "Resources & Articles",
    education: "Education",
    business: "Business",
    scholarships: "Scholarships",
    eightMinRead: "8 min read",
    twelveMinRead: "12 min read",
    sixMinRead: "6 min read",
    tenMinRead: "10 min read",
    fifteenMinRead: "15 min read",
    sevenMinRead: "7 min read",
    march152024: "March 15, 2024",
    march102024: "March 10, 2024",
    march52024: "March 5, 2024",
    february282024: "February 28, 2024",
    february202024: "February 20, 2024",
    february152024: "February 15, 2024",
    johnDoe: "John Doe",
    readMore: "Read More",
    newsletterTitle: "Stay Updated with Global Opportunities",
    newsletterDescription: "Get the latest scholarship announcements, study abroad tips, and F&B industry insights delivered to your inbox.",
    enterEmailAddress: "Enter your email address",
    subscribe: "Subscribe",
    scholarshipGuidance: "Scholarship Guidance",
    universityAdmissions: "University Admissions",
    applicationAssistance: "Application Assistance",
    documentPreparation: "Document Preparation",
    universityAdmissions: "University Admissions",
    universitySelection: "University Selection",
    applicationReview: "Application Review",
    interviewPreparation: "Interview Preparation",
    visaApplicationAssistance: "Visa Application Assistance",
    visaDocumentPrep: "Visa Document Preparation",
    applicationFiling: "Application Filing",
    interviewCoaching: "Interview Coaching",
    koreanLanguagePreparation: "Korean Language Preparation",
    topikPreparation: "TOPIK Preparation",
    conversationPractice: "Conversation Practice",
    culturalOrientationAndAccommodation: "Cultural Orientation and Accommodation",
    bookConsultation: "Book Consultation",
    // Missing translations for Sitemap
    mainPages: "Main Pages",
    homepageDescription: "Homepage with company overview",
    contactDescription: "Get in touch with our team",
    blogResources: "Blog/Resources",
    blogDescription: "Latest articles and educational resources",
    successStoriesDescription: "Client testimonials and case studies",
    newsletter: "Newsletter",
    sitemapDescription: "Complete site navigation",
    studyInKoreaDescription: "Educational consulting and scholarship guidance",
    fbConsultingDescription: "Food & beverage business consulting",
    universityAdmissionsDescription: "Assistance with university applications",
    marketAnalysisDescription: "Business market research and analysis",
    sitemapTitle: "Site Map",
    sitemapSubtitle: "Complete navigation guide to all pages and sections of our website.",
    needHelpFinding: "Need Help Finding Something?",
    cantFindWhatLooking: "Can't find what you're looking for? Our team is here to help you navigate our services.",
    contactSupport: "Contact Support",
    allPagesMobileResponsive: "All pages are mobile-responsive and accessibility-friendly",
    // Missing translations for StudyPrograms
    scholarshipGuidanceDesc: "Comprehensive scholarship search and application assistance for Korean universities",
    universityAdmissionSupport: "University Admission Support",
    universityAdmissionSupportDesc: "Complete support for university applications and admissions process",
    visaApplicationAssistance: "Visa Application Assistance",
    visaApplicationAssistanceDesc: "Step-by-step guidance through the Korean visa application process",
    visaDocumentPrep: "Visa document preparation",
    languagePreparation: "Language Preparation",
    languagePreparationDesc: "Korean language and cultural preparation for international students",
    culturalOrientationAndAccommodation: "Cultural orientation and accommodation",
    studyProgramsTitle: "Study Programs & Services",
    studyProgramsSubtitle: "Comprehensive educational consulting services for your Korean study journey",
    // Missing translations for TermsOfService
    termsOfServiceTitle: "Terms of Service",
    termsOfServiceSubtitle: "Please read these terms carefully before using our services.",
    acceptanceOfTerms: "Acceptance of Terms",
    acceptanceDescription: "By accessing and using Kunda Pathways' services, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.",
    kundaPathwaysProvides: "Kunda Pathways provides:",
    educationalConsultingScholarshipGuidance: "Educational consulting and scholarship guidance",
    universityAdmissionAssistance: "University admission assistance",
    fbBusinessConsulting: "Food & beverage business consulting",
    marketAnalysisBusinessDevelopment: "Market analysis and business development support",
    visaApplicationRelocation: "Visa application and relocation assistance",
    userResponsibilities: "User Responsibilities",
    userResponsibilitiesDescription: "As a user of our services, you agree to:",
    provideAccurateInfo: "Provide accurate and complete information",
    maintainAccountConfidentiality: "Maintain the confidentiality of your account",
    useServicesLawfully: "Use our services only for lawful purposes",
    respectIntellectualProperty: "Respect intellectual property rights",
    followApplicableLaws: "Follow all applicable laws and regulations",
    limitationsDisclaimers: "Limitations and Disclaimers",
    limitationsDescription: "While we strive to provide accurate information and quality services, we cannot guarantee:",
    successfulAdmission: "Successful admission to educational institutions",
    approvalScholarshipVisa: "Approval of scholarship or visa applications",
    specificBusinessOutcomes: "Specific business outcomes or profits",
    availabilityPrograms: "Availability of programs or opportunities",
    servicesAdvisoryNature: "Our services are advisory in nature and success depends on various external factors.",
    paymentRefundPolicy: "Payment and Refund Policy",
    paymentTermsInclude: "Our payment terms include:",
    paymentRequiredBeforeService: "Payment is required before service delivery",
    refundsCaseByCase: "Refunds are considered on a case-by-case basis",
    serviceFeesNonRefundable: "Service fees are non-refundable once work has commenced",
    cancellationsWithin48Hours: "Cancellations must be made within 48 hours of booking",
    governingLaw: "Governing Law",
    governingLawDescription: "These terms shall be governed by and construed in accordance with the laws of South Korea. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of Seoul, South Korea.",
    questionsContactLegal: "Questions? Contact us at legal@kundapathways.com",
  },
  KO: {
    welcome: "환영합니다",
    home: "홈",
    about: "소개",
    services: "서비스",
    contact: "연락처",
    resources: "자료",
    blog: "블로그",
    privacyPolicy: "개인정보처리방침",
    termsOfService: "서비스 약관",
    sitemap: "사이트맵",
    studyInKorea: "한국에서 공부하기",
    fbConsulting: "식음료 컨설팅",
    universityAdmissions: "대학 입학",
    marketAnalysis: "시장 분석",
    backToHome: "홈으로 돌아가기",
    resourcesBlog: "자료 및 기사",
    education: "교육",
    business: "비즈니스",
    scholarships: "장학금",
    eightMinRead: "8분 읽기",
    twelveMinRead: "12분 읽기",
    sixMinRead: "6분 읽기",
    tenMinRead: "10분 읽기",
    fifteenMinRead: "15분 읽기",
    sevenMinRead: "7분 읽기",
    march152024: "2024년 3월 15일",
    march102024: "2024년 3월 10일",
    march52024: "2024년 3월 5일",
    february282024: "2024년 2월 28일",
    february202024: "2024년 2월 20일",
    february152024: "2024년 2월 15일",
    johnDoe: "홍길동",
    readMore: "더 읽기",
    newsletterTitle: "글로벌 기회 소식 받기",
    newsletterDescription: "최신 장학금 공지, 유학 팁, 식음료 산업 인사이트를 이메일로 받아보세요.",
    enterEmailAddress: "이메일 주소를 입력하세요",
    subscribe: "구독하기",
    scholarshipGuidance: "장학금 안내",
    universityAdmissions: "대학 입학",
    applicationAssistance: "지원서 지원",
    documentPreparation: "서류 준비",
    universityAdmissions: "대학 입학",
    universitySelection: "대학 선택",
    applicationReview: "지원서 검토",
    interviewPreparation: "면접 준비",
    visaApplicationAssistance: "비자 신청 지원",
    visaDocumentPrep: "비자 서류 준비",
    applicationFiling: "신청서 제출",
    interviewCoaching: "면접 코칭",
    koreanLanguagePreparation: "한국어 준비",
    topikPreparation: "TOPIK 준비",
    conversationPractice: "회화 연습",
    culturalOrientationAndAccommodation: "문화 오리엔테이션 및 숙박",
    bookConsultation: "상담 예약",
    // Missing translations for Sitemap
    mainPages: "메인 페이지",
    homepageDescription: "회사 개요가 포함된 홈페이지",
    contactDescription: "저희 팀에 문의하세요",
    blogResources: "블로그/리소스",
    blogDescription: "최신 기사 및 교육 자료",
    successStoriesDescription: "고객 추천사 및 사례 연구",
    newsletter: "뉴스레터",
    sitemapDescription: "완전한 사이트 탐색",
    studyInKoreaDescription: "교육 컨설팅 및 장학금 안내",
    fbConsultingDescription: "식품 및 음료 사업 컨설팅",
    universityAdmissionsDescription: "대학 입학 지원",
    marketAnalysisDescription: "비즈니스 시장 조사 및 분석",
    sitemapTitle: "사이트 맵",
    sitemapSubtitle: "웹사이트의 모든 페이지와 섹션에 대한 완전한 탐색 가이드.",
    needHelpFinding: "찾는 것에 도움이 필요하신가요?",
    cantFindWhatLooking: "찾고 계신 것을 찾을 수 없나요? 저희 팀이 서비스 탐색을 도와드리겠습니다.",
    contactSupport: "지원팀 문의",
    allPagesMobileResponsive: "모든 페이지는 모바일 반응형이며 접근성이 좋습니다",
    // Missing translations for StudyPrograms
    scholarshipGuidanceDesc: "한국 대학교를 위한 종합적인 장학금 검색 및 지원 지원",
    universityAdmissionSupport: "대학 입학 지원",
    universityAdmissionSupportDesc: "대학 지원 및 입학 과정에 대한 완전한 지원",
    visaApplicationAssistance: "비자 신청 지원",
    visaApplicationAssistanceDesc: "한국 비자 신청 과정을 통한 단계별 안내",
    visaDocumentPrep: "비자 서류 준비",
    languagePreparation: "언어 준비",
    languagePreparationDesc: "국제 학생을 위한 한국어 및 문화 준비",
    culturalOrientationAndAccommodation: "문화적 오리엔테이션 및 숙박",
    studyProgramsTitle: "학습 프로그램 및 서비스",
    studyProgramsSubtitle: "한국 유학 여정을 위한 종합적인 교육 컨설팅 서비스",
    // Missing translations for TermsOfService
    termsOfServiceTitle: "서비스 약관",
    termsOfServiceSubtitle: "서비스를 사용하기 전에 이 약관을 주의 깊게 읽어주세요.",
    acceptanceOfTerms: "약관 동의",
    acceptanceDescription: "Kunda Pathways의 서비스에 액세스하고 사용함으로써 이 계약의 조건과 규정에 구속되는 데 동의합니다. 위 사항에 동의하지 않으시면 이 서비스를 사용하지 마십시오.",
    kundaPathwaysProvides: "Kunda Pathways는 다음을 제공합니다:",
    educationalConsultingScholarshipGuidance: "교육 컨설팅 및 장학금 안내",
    universityAdmissionAssistance: "대학 입학 지원",
    fbBusinessConsulting: "식품 및 음료 사업 컨설팅",
    marketAnalysisBusinessDevelopment: "시장 분석 및 사업 개발 지원",
    visaApplicationRelocation: "비자 신청 및 이주 지원",
    userResponsibilities: "사용자 책임",
    userResponsibilitiesDescription: "서비스 사용자로서 다음에 동의합니다:",
    provideAccurateInfo: "정확하고 완전한 정보 제공",
    maintainAccountConfidentiality: "계정의 기밀성 유지",
    useServicesLawfully: "합법적인 목적으로만 서비스 사용",
    respectIntellectualProperty: "지적 재산권 존중",
    followApplicableLaws: "모든 적용 가능한 법률 및 규정 준수",
    limitationsDisclaimers: "제한사항 및 면책조항",
    limitationsDescription: "정확한 정보와 양질의 서비스를 제공하기 위해 노력하지만 다음을 보장할 수는 없습니다:",
    successfulAdmission: "교육 기관 입학 성공",
    approvalScholarshipVisa: "장학금 또는 비자 신청 승인",
    specificBusinessOutcomes: "특정 비즈니스 결과 또는 이익",
    availabilityPrograms: "프로그램 또는 기회의 가용성",
    servicesAdvisoryNature: "저희 서비스는 자문 성격이며 성공은 다양한 외부 요인에 따라 달라집니다.",
    paymentRefundPolicy: "결제 및 환불 정책",
    paymentTermsInclude: "결제 조건은 다음과 같습니다:",
    paymentRequiredBeforeService: "서비스 제공 전 결제 필요",
    refundsCaseByCase: "환불은 사례별로 고려됩니다",
    serviceFeesNonRefundable: "작업이 시작되면 서비스 수수료는 환불되지 않습니다",
    cancellationsWithin48Hours: "예약 후 48시간 이내에 취소해야 합니다",
    governingLaw: "준거법",
    governingLawDescription: "이 약관은 대한민국 법률에 따라 관리되고 해석됩니다. 이 약관에 따른 모든 분쟁은 대한민국 서울 법원의 전속 관할권에 따릅니다.",
    questionsContactLegal: "질문이 있으시면 legal@kundapathways.com으로 연락주세요",
  },
  FR: {
    welcome: "Bienvenue",
    home: "Accueil",
    about: "À propos",
    services: "Services",
    contact: "Contact",
    resources: "Ressources",
    blog: "Blog",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    sitemap: "Plan du site",
    studyInKorea: "Étudier en Corée",
    fbConsulting: "Consultation F&B",
    universityAdmissions: "Admissions universitaires",
    marketAnalysis: "Analyse de marché",
    backToHome: "Retour à l'accueil",
    resourcesBlog: "Ressources & Articles",
    education: "Éducation",
    business: "Affaires",
    scholarships: "Bourses",
    eightMinRead: "8 min de lecture",
    twelveMinRead: "12 min de lecture",
    sixMinRead: "6 min de lecture",
    tenMinRead: "10 min de lecture",
    fifteenMinRead: "15 min de lecture",
    sevenMinRead: "7 min de lecture",
    march152024: "15 mars 2024",
    march102024: "10 mars 2024",
    march52024: "5 mars 2024",
    february282024: "28 février 2024",
    february202024: "20 février 2024",
    february152024: "15 février 2024",
    johnDoe: "Jean Dupont",
    readMore: "Lire la suite",
    newsletterTitle: "Restez informé des opportunités mondiales",
    newsletterDescription: "Recevez les dernières annonces de bourses, conseils d'études à l'étranger et informations sur l'industrie F&B directement dans votre boîte mail.",
    enterEmailAddress: "Entrez votre adresse e-mail",
    subscribe: "S'abonner",
    scholarshipGuidance: "Guidance pour les bourses",
    universityAdmissions: "Admissions universitaires",
    applicationAssistance: "Assistance à la candidature",
    documentPreparation: "Préparation des documents",
    universityAdmissions: "Admissions universitaires",
    universitySelection: "Sélection universitaire",
    applicationReview: "Revue de candidature",
    interviewPreparation: "Préparation à l'entretien",
    visaApplicationAssistance: "Assistance à la demande de visa",
    visaDocumentPrep: "Préparation des documents de visa",
    applicationFiling: "Dépôt de la demande",
    interviewCoaching: "Coaching d'entretien",
    koreanLanguagePreparation: "Préparation linguistique coréenne",
    topikPreparation: "Préparation TOPIK",
    conversationPractice: "Pratique de conversation",
    culturalOrientationAndAccommodation: "Orientation culturelle et hébergement",
    bookConsultation: "Réserver une consultation",
    // Missing translations for Sitemap
    mainPages: "Pages principales",
    homepageDescription: "Page d'accueil avec aperçu de l'entreprise",
    contactDescription: "Contactez notre équipe",
    blogResources: "Blog/Ressources",
    blogDescription: "Derniers articles et ressources éducatives",
    successStoriesDescription: "Témoignages clients et études de cas",
    newsletter: "Newsletter",
    sitemapDescription: "Navigation complète du site",
    studyInKoreaDescription: "Conseil éducatif et guidance de bourses",
    fbConsultingDescription: "Conseil en entreprise alimentaire et boissons",
    universityAdmissionsDescription: "Assistance aux candidatures universitaires",
    marketAnalysisDescription: "Recherche et analyse de marché commercial",
    sitemapTitle: "Plan du site",
    sitemapSubtitle: "Guide de navigation complet pour toutes les pages et sections de notre site web.",
    needHelpFinding: "Besoin d'aide pour trouver quelque chose ?",
    cantFindWhatLooking: "Vous ne trouvez pas ce que vous cherchez ? Notre équipe est là pour vous aider à naviguer dans nos services.",
    contactSupport: "Contacter le support",
    allPagesMobileResponsive: "Toutes les pages sont adaptées aux mobiles et accessibles",
    // Missing translations for StudyPrograms
    scholarshipGuidanceDesc: "Recherche complète de bourses et assistance aux candidatures pour les universités coréennes",
    universityAdmissionSupport: "Support d'admission universitaire",
    universityAdmissionSupportDesc: "Support complet pour les candidatures universitaires et le processus d'admission",
    visaApplicationAssistance: "Assistance pour demande de visa",
    visaApplicationAssistanceDesc: "Guidance étape par étape à travers le processus de demande de visa coréen",
    visaDocumentPrep: "Préparation des documents de visa",
    languagePreparation: "Préparation linguistique",
    languagePreparationDesc: "Préparation linguistique et culturelle coréenne pour étudiants internationaux",
    culturalOrientationAndAccommodation: "Orientation culturelle et hébergement",
    studyProgramsTitle: "Programmes d'études et services",
    studyProgramsSubtitle: "Services de conseil éducatif complets pour votre parcours d'études coréennes",
    // Missing translations for TermsOfService
    termsOfServiceTitle: "Conditions de service",
    termsOfServiceSubtitle: "Veuillez lire attentivement ces conditions avant d'utiliser nos services.",
    acceptanceOfTerms: "Acceptation des conditions",
    acceptanceDescription: "En accédant et en utilisant les services de Kunda Pathways, vous acceptez et vous engagez à être lié par les termes et dispositions de cet accord. Si vous n'acceptez pas de respecter ce qui précède, veuillez ne pas utiliser ce service.",
    kundaPathwaysProvides: "Kunda Pathways fournit :",
    educationalConsultingScholarshipGuidance: "Conseil éducatif et guidance de bourses",
    universityAdmissionAssistance: "Assistance à l'admission universitaire",
    fbBusinessConsulting: "Conseil en entreprise alimentaire et boissons",
    marketAnalysisBusinessDevelopment: "Analyse de marché et support de développement commercial",
    visaApplicationRelocation: "Demande de visa et assistance à la relocalisation",
    userResponsibilities: "Responsabilités de l'utilisateur",
    userResponsibilitiesDescription: "En tant qu'utilisateur de nos services, vous acceptez de :",
    provideAccurateInfo: "Fournir des informations exactes et complètes",
    maintainAccountConfidentiality: "Maintenir la confidentialité de votre compte",
    useServicesLawfully: "Utiliser nos services uniquement à des fins légales",
    respectIntellectualProperty: "Respecter les droits de propriété intellectuelle",
    followApplicableLaws: "Suivre toutes les lois et réglementations applicables",
    limitationsDisclaimers: "Limitations et avertissements",
    limitationsDescription: "Bien que nous nous efforcions de fournir des informations exactes et des services de qualité, nous ne pouvons pas garantir :",
    successfulAdmission: "Admission réussie dans les institutions éducatives",
    approvalScholarshipVisa: "Approbation des demandes de bourse ou de visa",
    specificBusinessOutcomes: "Résultats commerciaux ou profits spécifiques",
    availabilityPrograms: "Disponibilité des programmes ou opportunités",
    servicesAdvisoryNature: "Nos services sont de nature consultative et le succès dépend de divers facteurs externes.",
    paymentRefundPolicy: "Politique de paiement et de remboursement",
    paymentTermsInclude: "Nos conditions de paiement incluent :",
    paymentRequiredBeforeService: "Le paiement est requis avant la livraison du service",
    refundsCaseByCase: "Les remboursements sont considérés au cas par cas",
    serviceFeesNonRefundable: "Les frais de service ne sont pas remboursables une fois le travail commencé",
    cancellationsWithin48Hours: "Les annulations doivent être faites dans les 48 heures suivant la réservation",
    governingLaw: "Loi applicable",
    governingLawDescription: "Ces conditions seront régies et interprétées conformément aux lois de la Corée du Sud. Tout litige découlant de ces conditions sera soumis à la juridiction exclusive des tribunaux de Séoul, Corée du Sud.",
    questionsContactLegal: "Des questions ? Contactez-nous à legal@kundapathways.com",
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: "EN",
  setLanguage: () => {},
  translations: translations.EN,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState("EN");

  useEffect(() => {
    const savedLang = localStorage.getItem("language");
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang: string) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem("language", lang);
      window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
