import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";

interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  translations: Translations;
}

const translations = {
  EN: {
    welcome: "Welcome",
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    resources: "Resources",
    blog: "Blog",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    sitemap: "Sitemap",
    studyInKorea: "Study in Korea",
    fbConsulting: "F&B Consulting",
    universityAdmissions: "University Admissions",
    marketAnalysis: "Market Analysis",
    backToHome: "Back to Home",
    resourcesBlog: "Resources & Articles",
    education: "Education",
    business: "Business",
    scholarships: "Scholarships",
    eightMinRead: "8 min read",
    twelveMinRead: "12 min read",
    sixMinRead: "6 min read",
    tenMinRead: "10 min read",
    fifteenMinRead: "15 min read",
    sevenMinRead: "7 min read",
    march152024: "March 15, 2024",
    march102024: "March 10, 2024",
    march52024: "March 5, 2024",
    february282024: "February 28, 2024",
    february202024: "February 20, 2024",
    february152024: "February 15, 2024",
    johnDoe: "John Doe",
    readMore: "Read More",
    newsletterTitle: "Stay Updated with Global Opportunities",
    newsletterDescription: "Get the latest scholarship announcements, study abroad tips, and F&B industry insights delivered to your inbox.",
    enterEmailAddress: "Enter your email address",
    subscribe: "Subscribe",
    scholarshipGuidance: "Scholarship Guidance",
    applicationAssistance: "Application Assistance",
    documentPreparation: "Document Preparation",
    universitySelection: "University Selection",
    applicationReview: "Application Review",
    interviewPreparation: "Interview Preparation",
    visaApplicationAssistance: "Visa Application Assistance",
    visaDocumentPrep: "Visa Document Preparation",
    applicationFiling: "Application Filing",
    interviewCoaching: "Interview Coaching",
    koreanLanguagePreparation: "Korean Language Preparation",
    topikPreparation: "TOPIK Preparation",
    conversationPractice: "Conversation Practice",
    culturalOrientationAndAccommodation: "Cultural Orientation and Accommodation",
    bookConsultation: "Book Consultation",
    mainPages: "Main Pages",
    homepageDescription: "Homepage with company overview",
    contactDescription: "Get in touch with our team",
    blogResources: "Blog/Resources",
    blogDescription: "Latest articles and educational resources",
    successStoriesDescription: "Client testimonials and case studies",
    newsletter: "Newsletter",
    sitemapDescription: "Complete site navigation",
    studyInKoreaDescription: "Educational consulting and scholarship guidance",
    fbConsultingDescription: "Food & beverage business consulting",
    universityAdmissionsDescription: "Assistance with university applications",
    marketAnalysisDescription: "Business market research and analysis",
    sitemapTitle: "Site Map",
    sitemapSubtitle: "Complete navigation guide to all pages and sections of our website.",
    needHelpFinding: "Need Help Finding Something?",
    cantFindWhatLooking: "Can't find what you're looking for? Our team is here to help you navigate our services.",
    contactSupport: "Contact Support",
    allPagesMobileResponsive: "All pages are mobile-responsive and accessibility-friendly",
    scholarshipGuidanceDesc: "Comprehensive scholarship search and application assistance for Korean universities",
    universityAdmissionSupport: "University Admission Support",
    universityAdmissionSupportDesc: "Complete support for university applications and admissions process",
    visaApplicationAssistanceDesc: "Step-by-step guidance through the Korean visa application process",
    languagePreparation: "Language Preparation",
    languagePreparationDesc: "Korean language and cultural preparation for international students",
    studyProgramsTitle: "Study Programs & Services",
    studyProgramsSubtitle: "Comprehensive educational consulting services for your Korean study journey",
    termsOfServiceTitle: "Terms of Service",
    termsOfServiceSubtitle: "Please read these terms carefully before using our services.",
    acceptanceOfTerms: "Acceptance of Terms",
    acceptanceDescription: "By accessing and using Kunda Pathways' services, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.",
    kundaPathwaysProvides: "Kunda Pathways provides:",
    educationalConsultingScholarshipGuidance: "Educational consulting and scholarship guidance",
    universityAdmissionAssistance: "University admission assistance",
    fbBusinessConsulting: "Food & beverage business consulting",
    marketAnalysisBusinessDevelopment: "Market analysis and business development support",
    visaApplicationRelocation: "Visa application and relocation assistance",
    userResponsibilities: "User Responsibilities",
    userResponsibilitiesDescription: "As a user of our services, you agree to:",
    provideAccurateInfo: "Provide accurate and complete information",
    maintainAccountConfidentiality: "Maintain the confidentiality of your account",
    useServicesLawfully: "Use our services only for lawful purposes",
    respectIntellectualProperty: "Respect intellectual property rights",
    followApplicableLaws: "Follow all applicable laws and regulations",
    limitationsDisclaimers: "Limitations and Disclaimers",
    limitationsDescription: "While we strive to provide accurate information and quality services, we cannot guarantee:",
    successfulAdmission: "Successful admission to educational institutions",
    approvalScholarshipVisa: "Approval of scholarship or visa applications",
    specificBusinessOutcomes: "Specific business outcomes or profits",
    availabilityPrograms: "Availability of programs or opportunities",
    servicesAdvisoryNature: "Our services are advisory in nature and success depends on various external factors.",
    paymentRefundPolicy: "Payment and Refund Policy",
    paymentTermsInclude: "Our payment terms include:",
    paymentRequiredBeforeService: "Payment is required before service delivery",
    refundsCaseByCase: "Refunds are considered on a case-by-case basis",
    serviceFeesNonRefundable: "Service fees are non-refundable once work has commenced",
    cancellationsWithin48Hours: "Cancellations must be made within 48 hours of booking",
    governingLaw: "Governing Law",
    governingLawDescription: "These terms shall be governed by and construed in accordance with the laws of South Korea. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of Seoul, South Korea.",
    questionsContactLegal: "Questions? Contact us at legal@kundapathways.com",
    heroTitle: "Your Gateway to Global Education and Business Success",
    heroSubtitle: "Expert guidance for Korean university admissions, scholarships, and F&B business consulting",
    exploreStudyPrograms: "Explore Study Programs",
    studentsAssisted: "Students Assisted",
    countriesReached: "Countries Reached",
    foodScienceExpert: "Food Science Expert",
    blogPost1Title: "Complete Guide to Korean University Scholarships 2024",
    blogPost1Excerpt: "Everything you need to know about applying for scholarships in Korea, including KGSP and university-specific programs.",
    blogPost2Title: "F&B Market Entry Strategies for Korea",
    blogPost2Excerpt: "Learn the essential steps to successfully enter the Korean food and beverage market with expert insights.",
    blogPost3Title: "TOPIK Preparation: Your Path to Korean Universities",
    blogPost3Excerpt: "Master the Test of Proficiency in Korean with our comprehensive preparation guide.",
    latest: "Latest",
    resourcesDescription: "Explore our collection of guides, tips, and insights",
    viewAllResources: "View All Resources",
    footerDescription: "Your trusted partner for Korean education and F&B business success.",
    quickLinks: "Quick Links",
    aboutUs: "About Us",
    legal: "Legal",
    contactInfo: "Contact Info",
    allRightsReserved: "All rights reserved.",
    newsletterThankYou: "Thank you for subscribing!",
    ourTrustedPartners: "Our Trusted Partners",
    partnerDescription: "We work with leading institutions and organizations",
    scholarshipDescription: "Find and apply for the best scholarship opportunities",
    scholarshipSearch: "Scholarship Search",
    universityDescription: "Complete support for university applications",
    visaDescription: "Professional visa application assistance",
    languageDescription: "Korean language and cultural preparation",
    culturalOrientation: "Cultural Orientation",
    businessDescription: "F&B business consulting and market entry",
    marketResearch: "Market Research",
    businessPlanning: "Business Planning",
    strategyDevelopment: "Strategy Development",
    marketSizing: "Market Sizing",
    competitorAnalysis: "Competitor Analysis",
    trendIdentification: "Trend Identification",
    productDescription: "Product development and innovation support",
    recipeDevelopment: "Recipe Development",
    productTesting: "Product Testing",
    complianceDescription: "Food safety and regulatory compliance",
    safetyStandards: "Safety Standards",
    certificationSupport: "Certification Support",
    complianceAudits: "Compliance Audits",
    ourServices: "Our Services",
    servicesDescription: "Comprehensive solutions for education and business",
    startYourJourney: "Start Your Journey",
    getExpertConsultation: "Get Expert Consultation",
    letsStartYourJourney: "Let's Start Your Journey",
    journeyDescription: "Book a consultation to discuss your goals",
    getFullConsultation: "Get Full Consultation",
    viewAllPackagesPricing: "View All Packages & Pricing",
    successStories: "Success Stories",
    testimonialSubtitle: "Hear from our satisfied clients",
    scheduleFreeFifteenMinuteConsultation: "Schedule Free 15-minute Consultation",
    advisorName: "Dr. Sarah Kim",
    advisorTitle: "Education & F&B Consultant",
    professionalSummary: "Professional Summary",
    educationExpertise: "Education Expertise",
    koreanGovernmentScholarshipProgram: "Korean Government Scholarship Program (KGSP)",
    universityAdmissionStrategies: "University Admission Strategies",
    visaApplicationGuidance: "Visa Application Guidance",
    culturalAdaptationSupport: "Cultural Adaptation Support",
    fbExpertise: "F&B Expertise",
    marketAnalysisEntryStrategies: "Market Analysis & Entry Strategies",
    productDevelopmentInnovation: "Product Development & Innovation",
    businessPlanningFunding: "Business Planning & Funding",
    keyAchievements: "Key Achievements",
    getInTouch: "Get in Touch",
    officeHours: "Office Hours",
    mondayToFriday: "Monday to Friday",
    saturdaySunday: "Saturday & Sunday",
    koreanTime: "Korean Time",
    myMission: "My Mission",
    missionStatement: "To empower individuals and businesses to achieve their goals through expert guidance and personalized support.",
    hotelBooking: "Hotel Booking",
    phoneConsultation: "Phone Consultation",
    reviewConsultation: "Review Consultation",
    consultationDetails: "Consultation Details",
    fullName: "Full Name",
    email: "Email",
    selectedService: "Selected Service",
    totalPrice: "Total Price",
    paymentMethods: "Payment Methods",
    payWithCard: "Pay with Card",
    payWithMobile: "Pay with Mobile",
    payWithBank: "Pay with Bank",
    backToEdit: "Back to Edit",
    phone: "Phone",
    selectService: "Select Service",
    preferredDate: "Preferred Date",
    preferredTime: "Preferred Time",
    reviewConsultationRequest: "Review Consultation Request",
    privacyPolicyTitle: "Privacy Policy",
    privacyPolicySubtitle: "Your privacy is important to us",
    informationWeCollect: "Information We Collect",
    privacyCollectDescription: "We collect information you provide directly to us, such as:",
    personalIdentificationInfo: "Personal identification information",
    educationalBackground: "Educational background",
    professionalExperience: "Professional experience",
    communicationPreferences: "Communication preferences",
    howWeUseYourInfo: "How We Use Your Information",
    privacyUseDescription: "We use the information we collect to:",
    providePersonalizedServices: "Provide personalized services",
    processScholarshipApplications: "Process scholarship applications",
    sendRelevantUpdates: "Send relevant updates",
    improveServices: "Improve our services",
    complyLegalObligations: "Comply with legal obligations",
    dataSecurity: "Data Security",
    dataSecurityDescription: "We implement appropriate security measures to protect your information:",
    encryptedDataTransmission: "Encrypted data transmission",
    regularSecurityAudits: "Regular security audits",
    accessControls: "Access controls",
    employeeTraining: "Employee training",
    informationSharing: "Information Sharing",
    privacySharingDescription: "We may share your information with:",
    educationalInstitutions: "Educational institutions",
    governmentAgencies: "Government agencies",
    trustedServiceProviders: "Trusted service providers",
    legalAuthorities: "Legal authorities when required",
    neverSellPersonalInfo: "We never sell your personal information.",
    yourRights: "Your Rights",
    yourRightsDescription: "You have the right to:",
    accessReviewPersonalInfo: "Access and review your personal information",
    requestCorrections: "Request corrections",
    requestDeletion: "Request deletion",
    optOutMarketing: "Opt out of marketing communications",
    dataPortability: "Data portability",
    lastUpdatedMarch2024: "Last updated: March 2024.",
    questionsContact: "Questions? Contact us at privacy@kundapathways.com"
  },
  KO: {
    welcome: "환영합니다",
    home: "홈",
    about: "소개",
    services: "서비스",
    contact: "연락처",
    resources: "자료",
    blog: "블로그",
    privacyPolicy: "개인정보처리방침",
    termsOfService: "서비스 약관",
    sitemap: "사이트맵",
    studyInKorea: "한국에서 공부하기",
    fbConsulting: "식음료 컨설팅",
    universityAdmissions: "대학 입학",
    marketAnalysis: "시장 분석",
    backToHome: "홈으로 돌아가기",
    resourcesBlog: "자료 및 기사",
    education: "교육",
    business: "비즈니스",
    scholarships: "장학금",
    eightMinRead: "8분 읽기",
    twelveMinRead: "12분 읽기",
    sixMinRead: "6분 읽기",
    tenMinRead: "10분 읽기",
    fifteenMinRead: "15분 읽기",
    sevenMinRead: "7분 읽기",
    march152024: "2024년 3월 15일",
    march102024: "2024년 3월 10일",
    march52024: "2024년 3월 5일",
    february282024: "2024년 2월 28일",
    february202024: "2024년 2월 20일",
    february152024: "2024년 2월 15일",
    johnDoe: "홍길동",
    readMore: "더 읽기",
    newsletterTitle: "글로벌 기회 소식 받기",
    newsletterDescription: "최신 장학금 공지, 유학 팁, 식음료 산업 인사이트를 이메일로 받아보세요.",
    enterEmailAddress: "이메일 주소를 입력하세요",
    subscribe: "구독하기",
    scholarshipGuidance: "장학금 안내",
    applicationAssistance: "지원서 지원",
    documentPreparation: "서류 준비",
    universitySelection: "대학 선택",
    applicationReview: "지원서 검토",
    interviewPreparation: "면접 준비",
    visaApplicationAssistance: "비자 신청 지원",
    visaDocumentPrep: "비자 서류 준비",
    applicationFiling: "신청서 제출",
    interviewCoaching: "면접 코칭",
    koreanLanguagePreparation: "한국어 준비",
    topikPreparation: "TOPIK 준비",
    conversationPractice: "회화 연습",
    culturalOrientationAndAccommodation: "문화 오리엔테이션 및 숙박",
    bookConsultation: "상담 예약",
    mainPages: "메인 페이지",
    homepageDescription: "회사 개요가 포함된 홈페이지",
    contactDescription: "저희 팀에 문의하세요",
    blogResources: "블로그/리소스",
    blogDescription: "최신 기사 및 교육 자료",
    successStoriesDescription: "고객 추천사 및 사례 연구",
    newsletter: "뉴스레터",
    sitemapDescription: "완전한 사이트 탐색",
    studyInKoreaDescription: "교육 컨설팅 및 장학금 안내",
    fbConsultingDescription: "식품 및 음료 사업 컨설팅",
    universityAdmissionsDescription: "대학 입학 지원",
    marketAnalysisDescription: "비즈니스 시장 조사 및 분석",
    sitemapTitle: "사이트 맵",
    sitemapSubtitle: "웹사이트의 모든 페이지와 섹션에 대한 완전한 탐색 가이드.",
    needHelpFinding: "찾는 것에 도움이 필요하신가요?",
    cantFindWhatLooking: "찾고 계신 것을 찾을 수 없나요? 저희 팀이 서비스 탐색을 도와드리겠습니다.",
    contactSupport: "지원팀 문의",
    allPagesMobileResponsive: "모든 페이지는 모바일 반응형이며 접근성이 좋습니다",
    scholarshipGuidanceDesc: "한국 대학교를 위한 종합적인 장학금 검색 및 지원 지원",
    universityAdmissionSupport: "대학 입학 지원",
    universityAdmissionSupportDesc: "대학 지원 및 입학 과정에 대한 완전한 지원",
    visaApplicationAssistanceDesc: "한국 비자 신청 과정을 통한 단계별 안내",
    languagePreparation: "언어 준비",
    languagePreparationDesc: "국제 학생을 위한 한국어 및 문화 준비",
    studyProgramsTitle: "학습 프로그램 및 서비스",
    studyProgramsSubtitle: "한국 유학 여정을 위한 종합적인 교육 컨설팅 서비스",
    termsOfServiceTitle: "서비스 약관",
    termsOfServiceSubtitle: "서비스를 사용하기 전에 이 약관을 주의 깊게 읽어주세요.",
    acceptanceOfTerms: "약관 동의",
    acceptanceDescription: "Kunda Pathways의 서비스에 액세스하고 사용함으로써 이 계약의 조건과 규정에 구속되는 데 동의합니다.",
    kundaPathwaysProvides: "Kunda Pathways는 다음을 제공합니다:",
    educationalConsultingScholarshipGuidance: "교육 컨설팅 및 장학금 안내",
    universityAdmissionAssistance: "대학 입학 지원",
    fbBusinessConsulting: "식품 및 음료 사업 컨설팅",
    marketAnalysisBusinessDevelopment: "시장 분석 및 사업 개발 지원",
    visaApplicationRelocation: "비자 신청 및 이주 지원",
    userResponsibilities: "사용자 책임",
    userResponsibilitiesDescription: "서비스 사용자로서 다음에 동의합니다:",
    provideAccurateInfo: "정확하고 완전한 정보 제공",
    maintainAccountConfidentiality: "계정의 기밀성 유지",
    useServicesLawfully: "합법적인 목적으로만 서비스 사용",
    respectIntellectualProperty: "지적 재산권 존중",
    followApplicableLaws: "모든 적용 가능한 법률 및 규정 준수",
    limitationsDisclaimers: "제한사항 및 면책조항",
    limitationsDescription: "정확한 정보와 양질의 서비스를 제공하기 위해 노력하지만 다음을 보장할 수는 없습니다:",
    successfulAdmission: "교육 기관 입학 성공",
    approvalScholarshipVisa: "장학금 또는 비자 신청 승인",
    specificBusinessOutcomes: "특정 비즈니스 결과 또는 이익",
    availabilityPrograms: "프로그램 또는 기회의 가용성",
    servicesAdvisoryNature: "저희 서비스는 자문 성격이며 성공은 다양한 외부 요인에 따라 달라집니다.",
    paymentRefundPolicy: "결제 및 환불 정책",
    paymentTermsInclude: "결제 조건은 다음과 같습니다:",
    paymentRequiredBeforeService: "서비스 제공 전 결제 필요",
    refundsCaseByCase: "환불은 사례별로 고려됩니다",
    serviceFeesNonRefundable: "서비스 수수료는 환불되지 않습니다",
    cancellationsWithin48Hours: "예약 후 48시간 이내에 취소해야 합니다",
    governingLaw: "준거법",
    governingLawDescription: "이 약관은 대한민국 법률에 따라 관리되고 해석됩니다.",
    questionsContactLegal: "질문이 있으시면 legal@kundapathways.com으로 연락주세요",
    blogPost1Title: "2024년 한국 대학 장학금 완전 가이드",
    blogPost1Excerpt: "KGSP와 대학별 프로그램을 포함한 한국 장학금 신청에 대해 알아야 할 모든 것.",
    blogPost2Title: "한국 F&B 시장 진입 전략",
    blogPost2Excerpt: "전문가 통찰력으로 한국 식음료 시장에 성공적으로 진입하는 필수 단계를 배우세요.",
    blogPost3Title: "TOPIK 준비: 한국 대학으로의 길",
    blogPost3Excerpt: "종합적인 준비 가이드로 한국어능력시험을 마스터하세요.",
    latest: "최신",
    resourcesDescription: "가이드, 팁, 인사이트 컬렉션을 탐색하세요",
    viewAllResources: "모든 리소스 보기",
    footerDescription: "한국 교육 및 F&B 비즈니스 성공을 위한 신뢰할 수 있는 파트너.",
    quickLinks: "빠른 링크",
    aboutUs: "회사 소개",
    legal: "법적 정보",
    contactInfo: "연락처 정보",
    allRightsReserved: "모든 권리 보유.",
    newsletterThankYou: "구독해 주셔서 감사합니다!",
    ourTrustedPartners: "신뢰할 수 있는 파트너",
    partnerDescription: "선도적인 기관 및 조직과 협력합니다",
    scholarshipDescription: "최고의 장학금 기회를 찾고 신청하세요",
    scholarshipSearch: "장학금 검색",
    universityDescription: "대학 지원을 위한 완전한 지원",
    visaDescription: "전문 비자 신청 지원",
    languageDescription: "한국어 및 문화 준비",
    culturalOrientation: "문화 오리엔테이션",
    businessDescription: "F&B 비즈니스 컨설팅 및 시장 진입",
    marketResearch: "시장 조사",
    businessPlanning: "사업 계획",
    strategyDevelopment: "전략 개발",
    marketSizing: "시장 규모 분석",
    competitorAnalysis: "경쟁사 분석",
    trendIdentification: "트렌드 식별",
    productDescription: "제품 개발 및 혁신 지원",
    recipeDevelopment: "레시피 개발",
    productTesting: "제품 테스트",
    complianceDescription: "식품 안전 및 규제 준수",
    safetyStandards: "안전 기준",
    certificationSupport: "인증 지원",
    complianceAudits: "준수 감사",
    ourServices: "우리의 서비스",
    servicesDescription: "교육 및 비즈니스를 위한 종합 솔루션",
    startYourJourney: "여정 시작하기",
    getExpertConsultation: "전문가 상담 받기",
    letsStartYourJourney: "함께 여정을 시작합시다",
    journeyDescription: "목표를 논의하기 위한 상담 예약",
    getFullConsultation: "전체 상담 받기",
    viewAllPackagesPricing: "모든 패키지 및 가격 보기",
    successStories: "성공 사례",
    testimonialSubtitle: "만족한 고객들의 이야기를 들어보세요",
    scheduleFreeFifteenMinuteConsultation: "무료 15분 상담 예약",
    advisorName: "김사라 박사",
    advisorTitle: "교육 및 F&B 컨설턴트",
    professionalSummary: "전문가 요약",
    educationExpertise: "교육 전문성",
    koreanGovernmentScholarshipProgram: "한국정부장학금프로그램 (KGSP)",
    universityAdmissionStrategies: "대학 입학 전략",
    visaApplicationGuidance: "비자 신청 안내",
    culturalAdaptationSupport: "문화 적응 지원",
    fbExpertise: "F&B 전문성",
    marketAnalysisEntryStrategies: "시장 분석 및 진입 전략",
    productDevelopmentInnovation: "제품 개발 및 혁신",
    businessPlanningFunding: "사업 계획 및 자금 조달",
    keyAchievements: "주요 성과",
    getInTouch: "연락하기",
    officeHours: "업무 시간",
    mondayToFriday: "월요일부터 금요일까지",
    saturdaySunday: "토요일 및 일요일",
    koreanTime: "한국 시간",
    myMission: "나의 사명",
    missionStatement: "전문 가이드와 맞춤형 지원을 통해 개인과 기업이 목표를 달성할 수 있도록 지원하는 것입니다.",
    hotelBooking: "호텔 예약",
    phoneConsultation: "전화 상담",
    reviewConsultation: "상담 검토",
    consultationDetails: "상담 세부사항",
    fullName: "성명",
    email: "이메일",
    selectedService: "선택된 서비스",
    totalPrice: "총 가격",
    paymentMethods: "결제 방법",
    payWithCard: "카드로 결제",
    payWithMobile: "모바일로 결제",
    payWithBank: "은행으로 결제",
    backToEdit: "편집으로 돌아가기",
    phone: "전화번호",
    selectService: "서비스 선택",
    preferredDate: "희망 날짜",
    preferredTime: "희망 시간",
    reviewConsultationRequest: "상담 요청 검토",
    privacyPolicyTitle: "개인정보처리방침",
    privacyPolicySubtitle: "귀하의 개인정보는 우리에게 중요합니다",
    informationWeCollect: "수집하는 정보",
    privacyCollectDescription: "다음과 같이 직접 제공해 주시는 정보를 수집합니다:",
    personalIdentificationInfo: "개인 식별 정보",
    educationalBackground: "교육 배경",
    professionalExperience: "전문 경험",
    communicationPreferences: "커뮤니케이션 선호도",
    howWeUseYourInfo: "정보 사용 방법",
    privacyUseDescription: "수집한 정보를 다음 용도로 사용합니다:",
    providePersonalizedServices: "맞춤형 서비스 제공",
    processScholarshipApplications: "장학금 신청 처리",
    sendRelevantUpdates: "관련 업데이트 발송",
    improveServices: "서비스 개선",
    complyLegalObligations: "법적 의무 준수",
    dataSecurity: "데이터 보안",
    dataSecurityDescription: "귀하의 정보를 보호하기 위해 적절한 보안 조치를 구현합니다:",
    encryptedDataTransmission: "암호화된 데이터 전송",
    regularSecurityAudits: "정기적인 보안 감사",
    accessControls: "액세스 제어",
    employeeTraining: "직원 교육",
    informationSharing: "정보 공유",
    privacySharingDescription: "다음과 정보를 공유할 수 있습니다:",
    educationalInstitutions: "교육 기관",
    governmentAgencies: "정부 기관",
    trustedServiceProviders: "신뢰할 수 있는 서비스 제공업체",
    legalAuthorities: "필요시 법적 당국",
    neverSellPersonalInfo: "개인정보를 판매하지 않습니다.",
    yourRights: "귀하의 권리",
    yourRightsDescription: "다음과 같은 권리가 있습니다:",
    accessReviewPersonalInfo: "개인정보 액세스 및 검토",
    requestCorrections: "수정 요청",
    requestDeletion: "삭제 요청",
    optOutMarketing: "마케팅 커뮤니케이션 수신 거부",
    dataPortability: "데이터 이동성",
    lastUpdatedMarch2024: "최종 업데이트: 2024년 3월.",
    questionsContact: "질문이 있으시면 privacy@kundapathways.com으로 연락주세요"
  },
  FR: {
    welcome: "Bienvenue",
    home: "Accueil",
    about: "À propos",
    services: "Services",
    contact: "Contact",
    resources: "Ressources",
    blog: "Blog",
    privacyPolicy: "Politique de confidentialité",
    termsOfService: "Conditions d'utilisation",
    sitemap: "Plan du site",
    studyInKorea: "Étudier en Corée",
    fbConsulting: "Consultation F&B",
    universityAdmissions: "Admissions universitaires",
    marketAnalysis: "Analyse de marché",
    backToHome: "Retour à l'accueil",
    resourcesBlog: "Ressources & Articles",
    education: "Éducation",
    business: "Affaires",
    scholarships: "Bourses",
    eightMinRead: "8 min de lecture",
    twelveMinRead: "12 min de lecture",
    sixMinRead: "6 min de lecture",
    tenMinRead: "10 min de lecture",
    fifteenMinRead: "15 min de lecture",
    sevenMinRead: "7 min de lecture",
    march152024: "15 mars 2024",
    march102024: "10 mars 2024",
    march52024: "5 mars 2024",
    february282024: "28 février 2024",
    february202024: "20 février 2024",
    february152024: "15 février 2024",
    johnDoe: "Jean Dupont",
    readMore: "Lire la suite",
    newsletterTitle: "Restez informé des opportunités mondiales",
    newsletterDescription: "Recevez les dernières annonces de bourses, conseils d'études à l'étranger et informations sur l'industrie F&B directement dans votre boîte mail.",
    enterEmailAddress: "Entrez votre adresse e-mail",
    subscribe: "S'abonner",
    scholarshipGuidance: "Guidance pour les bourses",
    applicationAssistance: "Assistance à la candidature",
    documentPreparation: "Préparation des documents",
    universitySelection: "Sélection universitaire",
    applicationReview: "Revue de candidature",
    interviewPreparation: "Préparation à l'entretien",
    visaApplicationAssistance: "Assistance à la demande de visa",
    visaDocumentPrep: "Préparation des documents de visa",
    applicationFiling: "Dépôt de la demande",
    interviewCoaching: "Coaching d'entretien",
    koreanLanguagePreparation: "Préparation linguistique coréenne",
    topikPreparation: "Préparation TOPIK",
    conversationPractice: "Pratique de conversation",
    culturalOrientationAndAccommodation: "Orientation culturelle et hébergement",
    bookConsultation: "Réserver une consultation",
    heroTitle: "Votre passerelle vers l'éducation mondiale et le succès commercial",
    heroSubtitle: "Guidance experte pour les admissions universitaires coréennes, bourses et conseil commercial F&B",
    exploreStudyPrograms: "Explorer les programmes d'études",
    studentsAssisted: "Étudiants assistés",
    countriesReached: "Pays atteints",
    foodScienceExpert: "Expert en sciences alimentaires",
    mainPages: "Pages principales",
    homepageDescription: "Page d'accueil avec aperçu de l'entreprise",
    contactDescription: "Contactez notre équipe",
    blogResources: "Blog/Ressources",
    blogDescription: "Derniers articles et ressources éducatives",
    successStoriesDescription: "Témoignages clients et études de cas",
    newsletter: "Newsletter",
    sitemapDescription: "Navigation complète du site",
    studyInKoreaDescription: "Conseil éducatif et guidance de bourses",
    fbConsultingDescription: "Conseil en entreprise alimentaire et boissons",
    universityAdmissionsDescription: "Assistance aux candidatures universitaires",
    marketAnalysisDescription: "Recherche et analyse de marché commercial",
    sitemapTitle: "Plan du site",
    sitemapSubtitle: "Guide de navigation complet pour toutes les pages et sections de notre site web.",
    needHelpFinding: "Besoin d'aide pour trouver quelque chose ?",
    cantFindWhatLooking: "Vous ne trouvez pas ce que vous cherchez ? Notre équipe est là pour vous aider à naviguer dans nos services.",
    contactSupport: "Contacter le support",
    allPagesMobileResponsive: "Toutes les pages sont adaptées aux mobiles et accessibles",
    scholarshipGuidanceDesc: "Recherche complète de bourses et assistance aux candidatures pour les universités coréennes",
    universityAdmissionSupport: "Support d'admission universitaire",
    universityAdmissionSupportDesc: "Support complet pour les candidatures universitaires et le processus d'admission",
    visaApplicationAssistanceDesc: "Guidance étape par étape à travers le processus de demande de visa coréen",
    languagePreparation: "Préparation linguistique",
    languagePreparationDesc: "Préparation linguistique et culturelle coréenne pour étudiants internationaux",
    studyProgramsTitle: "Programmes d'études et services",
    studyProgramsSubtitle: "Services de conseil éducatif complets pour votre parcours d'études coréennes",
    termsOfServiceTitle: "Conditions de service",
    termsOfServiceSubtitle: "Veuillez lire attentivement ces conditions avant d'utiliser nos services.",
    acceptanceOfTerms: "Acceptation des conditions",
    acceptanceDescription: "En accédant et en utilisant les services de Kunda Pathways, vous acceptez et vous engagez à être lié par les termes et dispositions de cet accord.",
    kundaPathwaysProvides: "Kunda Pathways fournit :",
    educationalConsultingScholarshipGuidance: "Conseil éducatif et guidance de bourses",
    universityAdmissionAssistance: "Assistance à l'admission universitaire",
    fbBusinessConsulting: "Conseil en entreprise alimentaire et boissons",
    marketAnalysisBusinessDevelopment: "Analyse de marché et support de développement commercial",
    visaApplicationRelocation: "Demande de visa et assistance à la relocalisation",
    userResponsibilities: "Responsabilités de l'utilisateur",
    userResponsibilitiesDescription: "En tant qu'utilisateur de nos services, vous acceptez de :",
    provideAccurateInfo: "Fournir des informations exactes et complètes",
    maintainAccountConfidentiality: "Maintenir la confidentialité de votre compte",
    useServicesLawfully: "Utiliser nos services uniquement à des fins légales",
    respectIntellectualProperty: "Respecter les droits de propriété intellectuelle",
    followApplicableLaws: "Suivre toutes les lois et réglementations applicables",
    limitationsDisclaimers: "Limitations et avertissements",
    limitationsDescription: "Bien que nous nous efforcions de fournir des informations exactes et des services de qualité, nous ne pouvons pas garantir :",
    successfulAdmission: "Admission réussie dans les institutions éducatives",
    approvalScholarshipVisa: "Approbation des demandes de bourse ou de visa",
    specificBusinessOutcomes: "Résultats commerciaux ou profits spécifiques",
    availabilityPrograms: "Disponibilité des programmes ou opportunités",
    servicesAdvisoryNature: "Nos services sont de nature consultative et le succès dépend de divers facteurs externes.",
    paymentRefundPolicy: "Politique de paiement et de remboursement",
    paymentTermsInclude: "Nos conditions de paiement incluent :",
    paymentRequiredBeforeService: "Le paiement est requis avant la livraison du service",
    refundsCaseByCase: "Les remboursements sont considérés au cas par cas",
    serviceFeesNonRefundable: "Les frais de service ne sont pas remboursables une fois le travail commencé",
    cancellationsWithin48Hours: "Les annulations doivent être faites dans les 48 heures suivant la réservation",
    governingLaw: "Loi applicable",
    governingLawDescription: "Ces conditions seront régies et interprétées conformément aux lois de la Corée du Sud.",
    questionsContactLegal: "Des questions ? Contactez-nous à legal@kundapathways.com",
    blogPost1Title: "Guide complet des bourses universitaires coréennes 2024",
    blogPost1Excerpt: "Tout ce que vous devez savoir sur les candidatures de bourses en Corée, y compris KGSP et les programmes spécifiques aux universités.",
    blogPost2Title: "Stratégies d'entrée sur le marché F&B pour la Corée",
    blogPost2Excerpt: "Apprenez les étapes essentielles pour entrer avec succès sur le marché coréen des aliments et boissons avec des insights d'experts.",
    blogPost3Title: "Préparation TOPIK : Votre chemin vers les universités coréennes",
    blogPost3Excerpt: "Maîtrisez le Test de compétence en coréen avec notre guide de préparation complet.",
    latest: "Dernières",
    resourcesDescription: "Explorez notre collection de guides, conseils et insights",
    viewAllResources: "Voir toutes les ressources",
    footerDescription: "Votre partenaire de confiance pour l'éducation coréenne et le succès commercial F&B.",
    quickLinks: "Liens rapides",
    aboutUs: "À propos de nous",
    legal: "Légal",
    contactInfo: "Informations de contact",
    allRightsReserved: "Tous droits réservés.",
    newsletterThankYou: "Merci de vous être abonné !",
    ourTrustedPartners: "Nos partenaires de confiance",
    partnerDescription: "Nous travaillons avec des institutions et organisations de premier plan",
    scholarshipDescription: "Trouvez et postulez aux meilleures opportunités de bourses",
    scholarshipSearch: "Recherche de bourses",
    universityDescription: "Support complet pour les candidatures universitaires",
    visaDescription: "Assistance professionnelle pour les demandes de visa",
    languageDescription: "Préparation linguistique et culturelle coréenne",
    culturalOrientation: "Orientation culturelle",
    businessDescription: "Conseil commercial F&B et entrée sur le marché",
    marketResearch: "Recherche de marché",
    businessPlanning: "Planification commerciale",
    strategyDevelopment: "Développement de stratégie",
    marketSizing: "Dimensionnement du marché",
    competitorAnalysis: "Analyse concurrentielle",
    trendIdentification: "Identification des tendances",
    productDescription: "Support de développement et d'innovation de produits",
    recipeDevelopment: "Développement de recettes",
    productTesting: "Tests de produits",
    complianceDescription: "Sécurité alimentaire et conformité réglementaire",
    safetyStandards: "Normes de sécurité",
    certificationSupport: "Support de certification",
    complianceAudits: "Audits de conformité",
    ourServices: "Nos services",
    servicesDescription: "Solutions complètes pour l'éducation et les affaires",
    startYourJourney: "Commencez votre parcours",
    getExpertConsultation: "Obtenez une consultation d'expert",
    letsStartYourJourney: "Commençons votre parcours",
    journeyDescription: "Réservez une consultation pour discuter de vos objectifs",
    getFullConsultation: "Obtenez une consultation complète",
    viewAllPackagesPricing: "Voir tous les forfaits et tarifs",
    successStories: "Histoires de succès",
    testimonialSubtitle: "Écoutez nos clients satisfaits",
    scheduleFreeFifteenMinuteConsultation: "Programmer une consultation gratuite de 15 minutes",
    advisorName: "Dr. Sarah Kim",
    advisorTitle: "Consultant en éducation et F&B",
    professionalSummary: "Résumé professionnel",
    educationExpertise: "Expertise en éducation",
    koreanGovernmentScholarshipProgram: "Programme de bourses du gouvernement coréen (KGSP)",
    universityAdmissionStrategies: "Stratégies d'admission universitaire",
    visaApplicationGuidance: "Guidance pour les demandes de visa",
    culturalAdaptationSupport: "Support d'adaptation culturelle",
    fbExpertise: "Expertise F&B",
    marketAnalysisEntryStrategies: "Analyse de marché et stratégies d'entrée",
    productDevelopmentInnovation: "Développement de produits et innovation",
    businessPlanningFunding: "Planification commerciale et financement",
    keyAchievements: "Réalisations clés",
    getInTouch: "Prendre contact",
    officeHours: "Heures de bureau",
    mondayToFriday: "Lundi au vendredi",
    saturdaySunday: "Samedi et dimanche",
    koreanTime: "Heure coréenne",
    myMission: "Ma mission",
    missionStatement: "Autonomiser les individus et les entreprises pour atteindre leurs objectifs grâce à des conseils d'experts et un support personnalisé.",
    hotelBooking: "Réservation d'hôtel",
    phoneConsultation: "Consultation téléphonique",
    reviewConsultation: "Révision de consultation",
    consultationDetails: "Détails de la consultation",
    fullName: "Nom complet",
    email: "E-mail",
    selectedService: "Service sélectionné",
    totalPrice: "Prix total",
    paymentMethods: "Méthodes de paiement",
    payWithCard: "Payer par carte",
    payWithMobile: "Payer par mobile",
    payWithBank: "Payer par banque",
    backToEdit: "Retour à l'édition",
    phone: "Téléphone",
    selectService: "Sélectionner un service",
    preferredDate: "Date préférée",
    preferredTime: "Heure préférée",
    reviewConsultationRequest: "Réviser la demande de consultation",
    privacyPolicyTitle: "Politique de confidentialité",
    privacyPolicySubtitle: "Votre confidentialité est importante pour nous",
    informationWeCollect: "Informations que nous collectons",
    privacyCollectDescription: "Nous collectons les informations que vous nous fournissez directement, telles que :",
    personalIdentificationInfo: "Informations d'identification personnelle",
    educationalBackground: "Antécédents éducatifs",
    professionalExperience: "Expérience professionnelle",
    communicationPreferences: "Préférences de communication",
    howWeUseYourInfo: "Comment nous utilisons vos informations",
    privacyUseDescription: "Nous utilisons les informations que nous collectons pour :",
    providePersonalizedServices: "Fournir des services personnalisés",
    processScholarshipApplications: "Traiter les demandes de bourses",
    sendRelevantUpdates: "Envoyer des mises à jour pertinentes",
    improveServices: "Améliorer nos services",
    complyLegalObligations: "Respecter les obligations légales",
    dataSecurity: "Sécurité des données",
    dataSecurityDescription: "Nous mettons en œuvre des mesures de sécurité appropriées pour protéger vos informations :",
    encryptedDataTransmission: "Transmission de données cryptées",
    regularSecurityAudits: "Audits de sécurité réguliers",
    accessControls: "Contrôles d'accès",
    employeeTraining: "Formation des employés",
    informationSharing: "Partage d'informations",
    privacySharingDescription: "Nous pouvons partager vos informations avec :",
    educationalInstitutions: "Institutions éducatives",
    governmentAgencies: "Agences gouvernementales",
    trustedServiceProviders: "Fournisseurs de services de confiance",
    legalAuthorities: "Autorités légales lorsque requis",
    neverSellPersonalInfo: "Nous ne vendons jamais vos informations personnelles.",
    yourRights: "Vos droits",
    yourRightsDescription: "Vous avez le droit de :",
    accessReviewPersonalInfo: "Accéder et réviser vos informations personnelles",
    requestCorrections: "Demander des corrections",
    requestDeletion: "Demander la suppression",
    optOutMarketing: "Vous désinscrire des communications marketing",
    dataPortability: "Portabilité des données",
    lastUpdatedMarch2024: "Dernière mise à jour : Mars 2024.",
    questionsContact: "Questions ? Contactez-nous à privacy@kundapathways.com"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: "EN",
  setLanguage: () => {},
  translations: translations.EN,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState("EN");

  useEffect(() => {
    const savedLang = localStorage.getItem("language");
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
    }
  }, []);

  const changeLanguage = (lang: string) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem("language", lang);
      window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, translations: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
