// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wugzcmqtlctrccixqpvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Z3pjbXF0bGN0cmNjaXhxcHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTkzODQsImV4cCI6MjA2NjA3NTM4NH0.vl8EZvd66U1tGHdt1R_brxPYQY0gJ6N0-WUal51A_bY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);